apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: siddharth67/solar-system:v11
        name: solar-system
        imagePullPolicy: Always
        ports: 
        - containerPort: 80
        resources:
          requests:
            cpu: 200m # Increased CPU request to match limit
            memory: 2Gi
          limits:
            cpu: 200m
            memory: 2Gi